#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""ROS helpers for Robot Savo localization Python diagnostics."""

from .adapters import (
    imu_to_dict,
    make_json_msg,
    make_status_payload,
    make_string_msg,
    odom_to_dict,
    parse_json_msg,
    quaternion_to_dict,
    safe_bool,
    safe_float,
    safe_int,
    transform_to_dict,
    validate_imu_frame,
    validate_odom_frames,
    vector3_to_dict,
)
from .params import (
    declare_if_missing,
    get_bool_param,
    get_float_list_param,
    get_float_param,
    get_int_list_param,
    get_int_param,
    get_non_negative_float_param,
    get_positive_float_param,
    get_positive_int_param,
    get_range_param,
    get_string_list_param,
    get_string_param,
    init_rclpy_if_needed,
)
from .qos_profiles import (
    command_qos,
    health_qos,
    imu_qos,
    latched_state_qos,
    odom_qos,
    state_qos,
)
from .topic_contract import (
    DEFAULT_TOPICS,
    LocalizationTopics,
    get_default_topics,
    make_localization_topics,
    normalize_topic_name,
    validate_localization_topics,
)

__all__ = [
    "DEFAULT_TOPICS",
    "LocalizationTopics",
    "command_qos",
    "declare_if_missing",
    "get_bool_param",
    "get_default_topics",
    "get_float_list_param",
    "get_float_param",
    "get_int_list_param",
    "get_int_param",
    "get_non_negative_float_param",
    "get_positive_float_param",
    "get_positive_int_param",
    "get_range_param",
    "get_string_list_param",
    "get_string_param",
    "health_qos",
    "imu_qos",
    "imu_to_dict",
    "init_rclpy_if_needed",
    "latched_state_qos",
    "make_json_msg",
    "make_localization_topics",
    "make_status_payload",
    "make_string_msg",
    "normalize_topic_name",
    "odom_qos",
    "odom_to_dict",
    "parse_json_msg",
    "quaternion_to_dict",
    "safe_bool",
    "safe_float",
    "safe_int",
    "state_qos",
    "transform_to_dict",
    "validate_imu_frame",
    "validate_localization_topics",
    "validate_odom_frames",
    "vector3_to_dict",
]
