metadata:
  geometry_profile: robot_savo_core_v1
  geometry_revision: 1
  geometry_sha256: a95eb7faada0963daf8b79198dbf0c667a3607d42cbf4769db42af3cfe981bbe
  generated_from: config/profiles/robot_savo_core_v1.yaml
robot_base_frame: base_footprint
footprint: "[[0.165, 0.120], [0.165, -0.120], [-0.165, -0.120], [-0.165, 0.120]]"
footprint_padding: 0.02
