frontier_explorer_node:
  ros__parameters:
    enabled: false

    map_topic: /map
    odom_topic: /odometry/filtered
    safety_stop_topic: /safety/stop

    status_topic: /savo_mapping/frontier_explorer/status
    goal_topic: /savo_mapping/frontier_explorer/goal
    goal_pose_topic: /savo_mapping/frontier_explorer/goal_pose

    publish_rate_hz: 5.0
    map_stale_timeout_s: 2.0
    odom_stale_timeout_s: 1.0

    require_odom: true
    publish_repeated_goal: false
    verbose_status_log: false