map_event_logger_node:
  ros__parameters:
    enabled: false

    log_path: maps/events/map_events.jsonl

    status_topic: /savo_mapping/map_event_logger/status
    event_topic: /savo_mapping/map_event_logger/event

    event_topics:
      - /savo_mapping/mode_command
      - /savo_mapping/frontier_explorer/goal
      - /savo_mapping/location_confirmation/result
      - /savo_mapping/semantic_landmark_recorder/result
      - /savo_mapping/apriltag_mapper/result
      - /savo_mapping/location_bridge/status

    publish_rate_hz: 5.0
    max_payload_chars: 20000
    publish_logged_event: true
    verbose_status_log: false