imu_node:
  ros__parameters:
    frame_id: imu_link

    imu_topic: /imu/data
    imu_state_topic: /savo_localization/imu_state
    diagnostics_topic: /diagnostics

    i2c_bus: 1
    i2c_address: 40   # 0x28

    mode: ndof
    publish_rate_hz: 25.0
    reset_on_start: true

    publish_orientation: true
    publish_magnetic_field: true
    publish_temperature: true
    publish_diagnostics: true

    orientation_covariance_roll: 0.05
    orientation_covariance_pitch: 0.05
    orientation_covariance_yaw: 0.10

    angular_velocity_covariance_x: 0.02
    angular_velocity_covariance_y: 0.02
    angular_velocity_covariance_z: 0.02

    linear_acceleration_covariance_x: 0.10
    linear_acceleration_covariance_y: 0.10
    linear_acceleration_covariance_z: 0.10