apriltag_mapper_node:
  ros__parameters:
    enabled: false

    observation_topic: /savo_mapping/apriltag_observation
    status_topic: /savo_mapping/apriltag_mapper/status
    result_topic: /savo_mapping/apriltag_mapper/result
    candidate_topic: /savo_mapping/location_candidate

    tag_database_path: maps/semantic/tag_database.json
    semantic_store_path: maps/semantic/semantic_landmarks.json

    publish_rate_hz: 5.0
    min_confidence: 0.30

    allow_unknown_tags: false
    unknown_label_prefix: Tag

    write_semantic_store: true
    require_tag_database: false
    require_semantic_store_path: false

    verbose_status_log: false