location_confirmation_node:
  ros__parameters:
    enabled: false

    semantic_store_path: maps/semantic/semantic_landmarks.json

    command_topic: /savo_mapping/location_confirmation_command
    status_topic: /savo_mapping/location_confirmation/status
    result_topic: /savo_mapping/location_confirmation/result

    publish_rate_hz: 5.0

    require_semantic_store: false

    verbose_status_log: false