tag_database:
  ros__parameters:
    map_name: robot_savo_default
    default_family: tag36h11
    default_frame_id: map

    tags:
      - tag_id: 21
        label: A201
        key: a201
        area_type: destination
        priority: 3
        notes: Example destination tag.
        metadata:
          floor: 2
          building: example_building

      - tag_id: 22
        label: Info Desk
        key: info_desk
        area_type: service_area
        priority: 4
        notes: Example service/help point tag.
        metadata:
          floor: 1
          building: example_building

      - tag_id: 23
        label: Elevator Area
        key: elevator_area
        area_type: access_area
        priority: 3
        notes: Example elevator/access area tag.
        metadata:
          floor: 1
          building: example_building