# -*- coding: utf-8 -*-

"""Data models for Robot Savo active head fallback tools and tests."""

from __future__ import annotations

from savo_head.models.head_state import (
    MODE_AUTO,
    MODE_CENTERING,
    MODE_IDLE,
    MODE_MANUAL,
    VALID_HEAD_MODES,
    HeadRuntimeState,
    PanTiltLimits,
    PanTiltState,
    centered_state,
)
from savo_head.models.pantilt_command import (
    COMMAND_ABSOLUTE,
    COMMAND_CENTER,
    COMMAND_DELTA,
    COMMAND_HOLD,
    COMMAND_STOP,
    SOURCE_FALLBACK,
    SOURCE_MANUAL,
    SOURCE_SCAN,
    SOURCE_SYSTEM,
    VALID_COMMAND_SOURCES,
    VALID_COMMAND_TYPES,
    PanTiltCommand,
    absolute_command,
    center_command,
    delta_command,
    hold_command,
    manual_step_command,
    stop_command,
)
from savo_head.models.scan_status import (
    SCAN_MODE_STAGED,
    SCAN_PHASE_PAN,
    SCAN_PHASE_TILT_SWEEP,
    SCAN_STATE_DONE,
    SCAN_STATE_ERROR,
    SCAN_STATE_IDLE,
    SCAN_STATE_PAUSED,
    SCAN_STATE_RUNNING,
    TILT_DIRECTION_DOWN,
    TILT_DIRECTION_UP,
    VALID_SCAN_PHASES,
    VALID_SCAN_STATES,
    ScanProfile,
    ScanStatus,
    advance_scan_step,
    move_toward,
    next_pan_target_index,
    pause_scan,
    resume_scan,
    start_scan,
    stop_scan,
)
from savo_head.models.semantic_confirmation import (
    CONFIRMATION_CONFIRMED,
    CONFIRMATION_PENDING,
    CONFIRMATION_REJECTED,
    VALID_CONFIRMATION_STATES,
    VALID_CONFIRMATION_TYPES,
    AprilTagObservation,
    RobotPoseSnapshot,
    SemanticConfirmation,
    SemanticConfirmationPolicy,
    TagRegistration,
    make_confirmation,
    make_rejection,
)

__all__ = [
    # Head state
    "MODE_MANUAL",
    "MODE_AUTO",
    "MODE_IDLE",
    "MODE_CENTERING",
    "VALID_HEAD_MODES",
    "PanTiltLimits",
    "PanTiltState",
    "HeadRuntimeState",
    "centered_state",
    # Commands
    "COMMAND_ABSOLUTE",
    "COMMAND_DELTA",
    "COMMAND_CENTER",
    "COMMAND_HOLD",
    "COMMAND_STOP",
    "SOURCE_MANUAL",
    "SOURCE_SCAN",
    "SOURCE_SYSTEM",
    "SOURCE_FALLBACK",
    "VALID_COMMAND_TYPES",
    "VALID_COMMAND_SOURCES",
    "PanTiltCommand",
    "absolute_command",
    "delta_command",
    "center_command",
    "hold_command",
    "stop_command",
    "manual_step_command",
    # Scan
    "SCAN_MODE_STAGED",
    "SCAN_STATE_IDLE",
    "SCAN_STATE_RUNNING",
    "SCAN_STATE_PAUSED",
    "SCAN_STATE_DONE",
    "SCAN_STATE_ERROR",
    "SCAN_PHASE_PAN",
    "SCAN_PHASE_TILT_SWEEP",
    "TILT_DIRECTION_UP",
    "TILT_DIRECTION_DOWN",
    "VALID_SCAN_STATES",
    "VALID_SCAN_PHASES",
    "ScanProfile",
    "ScanStatus",
    "move_toward",
    "start_scan",
    "pause_scan",
    "resume_scan",
    "stop_scan",
    "next_pan_target_index",
    "advance_scan_step",
    # Semantic confirmation
    "CONFIRMATION_PENDING",
    "CONFIRMATION_CONFIRMED",
    "CONFIRMATION_REJECTED",
    "VALID_CONFIRMATION_STATES",
    "VALID_CONFIRMATION_TYPES",
    "TagRegistration",
    "AprilTagObservation",
    "RobotPoseSnapshot",
    "SemanticConfirmationPolicy",
    "SemanticConfirmation",
    "make_confirmation",
    "make_rejection",
]
