#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""Utility helpers for Robot Savo localization."""

from .clamp import (
    clamp,
    clamp_abs,
    clamp_float,
    clamp_int,
    clamp_signed_unit,
    clamp_unit,
    finite_or_default,
    is_finite_number,
    non_negative_or_default,
    positive_or_default,
)
from .frames import (
    LocalizationFrames,
    base_to_imu_pair,
    frame_pair,
    is_expected_base_frame,
    is_expected_imu_frame,
    is_expected_odom_frame,
    make_localization_frames,
    normalize_frame_id,
    odom_to_base_pair,
    require_expected_frame,
    validate_localization_frames,
)
from .logging import (
    format_json,
    format_kv,
    node_ready_message,
    node_start_message,
    node_stop_message,
    safe_str,
    status_line,
)
from .param_loader import (
    deep_merge_dicts,
    flatten_dict,
    get_nested_value,
    get_ros_parameters,
    load_merged_yaml,
    load_yaml_file,
    require_nested_value,
    require_ros_parameter,
    update_nested_value,
)
from .ratekeeper import RateKeeper
from .timing import (
    RateTracker,
    TimeoutWatch,
    age_s,
    elapsed_s,
    hz_to_period_s,
    is_stale,
    monotonic_now_s,
    period_s_to_hz,
    sleep_until_next_period,
    wall_now_s,
)
from .topic_names import (
    ensure_topic_namespace,
    is_absolute_topic,
    is_private_topic,
    join_topic,
    normalize_topic,
    topic_basename,
    topic_namespace,
)

__all__ = [
    "LocalizationFrames",
    "RateKeeper",
    "RateTracker",
    "TimeoutWatch",
    "age_s",
    "base_to_imu_pair",
    "clamp",
    "clamp_abs",
    "clamp_float",
    "clamp_int",
    "clamp_signed_unit",
    "clamp_unit",
    "deep_merge_dicts",
    "elapsed_s",
    "ensure_topic_namespace",
    "finite_or_default",
    "flatten_dict",
    "format_json",
    "format_kv",
    "frame_pair",
    "get_nested_value",
    "get_ros_parameters",
    "hz_to_period_s",
    "is_absolute_topic",
    "is_expected_base_frame",
    "is_expected_imu_frame",
    "is_expected_odom_frame",
    "is_finite_number",
    "is_private_topic",
    "is_stale",
    "join_topic",
    "load_merged_yaml",
    "load_yaml_file",
    "make_localization_frames",
    "monotonic_now_s",
    "node_ready_message",
    "node_start_message",
    "node_stop_message",
    "non_negative_or_default",
    "normalize_frame_id",
    "normalize_topic",
    "odom_to_base_pair",
    "period_s_to_hz",
    "positive_or_default",
    "require_expected_frame",
    "require_nested_value",
    "require_ros_parameter",
    "safe_str",
    "sleep_until_next_period",
    "status_line",
    "topic_basename",
    "topic_namespace",
    "update_nested_value",
    "validate_localization_frames",
    "wall_now_s",
]
