/base_battery_node:
  ros__parameters:
    i2c_bus: 1
    ads7830_address: 72
    ads7830_channel: 2
    ads7830_pcb_version: "v2"

    publish_rate_hz: 1.0

/base_battery_node_py:
  ros__parameters:
    i2c_bus: 1
    ads7830_address: 72
    ads7830_channel: 2
    ads7830_pcb_version: "v2"

    publish_rate_hz: 1.0
