/power_aggregator_node:
  ros__parameters:
    publish_rate_hz: 1.0
    stale_timeout_s: 5.0

    core_ups_expected: true
    edge_ups_expected: false
    base_battery_expected: true


/power_aggregator_node_py:
  ros__parameters:
    publish_rate_hz: 1.0
    stale_timeout_s: 5.0

    core_ups_expected: true
    edge_ups_expected: false
    base_battery_expected: true
