# -*- coding: utf-8 -*-

"""Shared ROS contracts for Robot Savo active head."""

from __future__ import annotations

from savo_head.contracts.frame_names import (
    BASE_LINK,
    FRAMES,
    HEAD_PAN_JOINT,
    HEAD_TILT_JOINT,
    MAP,
    ODOM,
    PANTILT_PAN_LINK,
    PANTILT_TILT_LINK,
    PI_CAMERA_LINK,
    PI_CAMERA_OPTICAL_FRAME,
    HeadFrameNames,
    get_frame_names,
    is_head_frame,
    is_robot_frame,
)
from savo_head.contracts.parameter_names import (
    PARAMETERS,
    HeadParameterNames,
    get_parameter_names,
    is_known_parameter,
)
from savo_head.contracts.topic_names import (
    APRILTAG_DETECTIONS,
    CAMERA_INFO,
    CAMERA_STATUS,
    CAMERA_STREAM_CMD,
    CAMERA_STREAM_STATE,
    DASHBOARD_TEXT,
    DIAGNOSTICS,
    EMERGENCY_CENTER,
    IMAGE_RAW,
    LOCATION_SAVE_REQUEST,
    LOCATION_SAVE_RESULT,
    MAPPING_SEMANTIC_SAVE_REQUEST,
    MAPPING_SEMANTIC_SAVE_RESULT,
    NAV_LOCATION_CONFIRMATION,
    NAMESPACE,
    PAN_TILT_CMD,
    PAN_TILT_STATE,
    SCAN_CMD,
    SCAN_STATE,
    SEMANTIC_CONFIRMATIONS,
    STATUS,
    TOPICS,
    HeadTopicNames,
    get_topic_names,
    is_savo_head_topic,
)

CONTRACT_MODULES = (
    "topic_names",
    "frame_names",
    "parameter_names",
)

__all__ = [
    "CONTRACT_MODULES",
    # Topics
    "NAMESPACE",
    "PAN_TILT_CMD",
    "PAN_TILT_STATE",
    "SCAN_CMD",
    "SCAN_STATE",
    "STATUS",
    "DASHBOARD_TEXT",
    "DIAGNOSTICS",
    "CAMERA_STREAM_CMD",
    "CAMERA_STREAM_STATE",
    "CAMERA_STATUS",
    "IMAGE_RAW",
    "CAMERA_INFO",
    "APRILTAG_DETECTIONS",
    "SEMANTIC_CONFIRMATIONS",
    "EMERGENCY_CENTER",
    "MAPPING_SEMANTIC_SAVE_REQUEST",
    "MAPPING_SEMANTIC_SAVE_RESULT",
    "LOCATION_SAVE_REQUEST",
    "LOCATION_SAVE_RESULT",
    "NAV_LOCATION_CONFIRMATION",
    "HeadTopicNames",
    "TOPICS",
    "get_topic_names",
    "is_savo_head_topic",
    # Frames
    "BASE_LINK",
    "PANTILT_PAN_LINK",
    "PANTILT_TILT_LINK",
    "PI_CAMERA_LINK",
    "PI_CAMERA_OPTICAL_FRAME",
    "HEAD_PAN_JOINT",
    "HEAD_TILT_JOINT",
    "MAP",
    "ODOM",
    "HeadFrameNames",
    "FRAMES",
    "get_frame_names",
    "is_head_frame",
    "is_robot_frame",
    # Parameters
    "HeadParameterNames",
    "PARAMETERS",
    "get_parameter_names",
    "is_known_parameter",
]
