"""Power data models for Robot Savo Python diagnostics and fallbacks."""

from __future__ import annotations

from savo_power.models.power_status import (
    BatterySource,
    PowerSourceStatus,
    PowerState,
    PowerStatusSummary,
    aggregate_overall_state,
    allows_normal_operation,
    battery_source_text,
    is_fault_state,
    is_safe_state,
    missing_source_status,
    more_severe_state,
    normalize_battery_source,
    normalize_power_state,
    not_expected_source_status,
    power_state_text,
    requires_operator_attention,
    source_label,
    source_status_from_state,
)

from savo_power.models.ups_reading import (
    UpsReading,
    evaluate_ups_state,
    is_ups_source,
    make_ups_error,
    make_ups_reading,
    make_ups_reading_from_raw,
    swap_word_bytes,
    ups_capacity_from_raw_word,
    ups_voltage_from_raw_word,
)

from savo_power.models.kit_battery_reading import (
    KitBatteryReading,
    ads7830_adc_voltage_from_byte,
    ads7830_battery_multiplier,
    ads7830_battery_voltage_from_byte,
    ads7830_channel_command,
    ads7830_reference_voltage,
    estimate_linear_soc_pct,
    evaluate_base_battery_state,
    is_valid_ads7830_channel,
    make_kit_battery_error,
    make_kit_battery_reading,
    make_kit_battery_reading_from_raw,
    normalize_pcb_version,
)

from savo_power.models.power_health import (
    PowerHealth,
    PowerHealthConfig,
    PowerHealthInput,
    PowerHealthLevel,
    PowerHealthResult,
    evaluate_power_health,
    evaluate_status_text_health,
    health_level_from_power_state,
    health_reason_for_state,
    make_health_text,
    normalize_health_level,
    state_from_status_text,
)


__all__ = [
    "BatterySource",
    "PowerSourceStatus",
    "PowerState",
    "PowerStatusSummary",
    "aggregate_overall_state",
    "allows_normal_operation",
    "battery_source_text",
    "is_fault_state",
    "is_safe_state",
    "missing_source_status",
    "more_severe_state",
    "normalize_battery_source",
    "normalize_power_state",
    "not_expected_source_status",
    "power_state_text",
    "requires_operator_attention",
    "source_label",
    "source_status_from_state",
    "UpsReading",
    "evaluate_ups_state",
    "is_ups_source",
    "make_ups_error",
    "make_ups_reading",
    "make_ups_reading_from_raw",
    "swap_word_bytes",
    "ups_capacity_from_raw_word",
    "ups_voltage_from_raw_word",
    "KitBatteryReading",
    "ads7830_adc_voltage_from_byte",
    "ads7830_battery_multiplier",
    "ads7830_battery_voltage_from_byte",
    "ads7830_channel_command",
    "ads7830_reference_voltage",
    "estimate_linear_soc_pct",
    "evaluate_base_battery_state",
    "is_valid_ads7830_channel",
    "make_kit_battery_error",
    "make_kit_battery_reading",
    "make_kit_battery_reading_from_raw",
    "normalize_pcb_version",
    "PowerHealth",
    "PowerHealthConfig",
    "PowerHealthInput",
    "PowerHealthLevel",
    "PowerHealthResult",
    "evaluate_power_health",
    "evaluate_status_text_health",
    "health_level_from_power_state",
    "health_reason_for_state",
    "make_health_text",
    "normalize_health_level",
    "state_from_status_text",
]
