"""Package-wide defaults for Robot Savo's RPLIDAR A1 stack."""

PACKAGE_NAME = "savo_lidar"
ROBOT_NAME = "Robot Savo"

DEFAULT_LIDAR_MODEL = "rplidar_a1"
DEFAULT_FRAME_ID = "laser"
DEFAULT_SCAN_TOPIC = "/scan"

DEFAULT_SERIAL_PORT = "/dev/ttyUSB0"
DEFAULT_BAUDRATE = 115200
DEFAULT_SCAN_MODE = "standard"

DEFAULT_MIN_RANGE_M = 0.15
DEFAULT_MAX_RANGE_M = 12.0

DEFAULT_SCAN_RATE_HZ = 5.5
DEFAULT_PUBLISH_RATE_HZ = 10.0

DEFAULT_HEALTH_TOPIC = "/savo_lidar/health"
DEFAULT_STATE_TOPIC = "/savo_lidar/state"
DEFAULT_SCAN_QUALITY_TOPIC = "/savo_lidar/scan_quality"
DEFAULT_HEARTBEAT_TOPIC = "/savo_lidar/heartbeat"
DEFAULT_WATCHDOG_STATE_TOPIC = "/savo_lidar/watchdog_state"

DEFAULT_STALE_TIMEOUT_S = 1.0
DEFAULT_HEALTH_PUBLISH_HZ = 1.0
DEFAULT_STATE_PUBLISH_HZ = 2.0
DEFAULT_HEARTBEAT_HZ = 1.0

DEFAULT_QUALITY_WARN_VALID_RATIO = 0.60
DEFAULT_QUALITY_ERROR_VALID_RATIO = 0.30

DEFAULT_FRONT_SECTOR_MIN_DEG = -45.0
DEFAULT_FRONT_SECTOR_MAX_DEG = 45.0

STATUS_OK = "OK"
STATUS_WARN = "WARN"
STATUS_ERROR = "ERROR"
STATUS_STALE = "STALE"
STATUS_OFFLINE = "OFFLINE"

BACKEND_REAL = "real"
BACKEND_DRYRUN = "dryrun"

SUPPORTED_BACKENDS = (BACKEND_REAL, BACKEND_DRYRUN)
SUPPORTED_LIDAR_MODELS = ("rplidar_a1",)