# -*- coding: utf-8 -*-

"""Utility helpers for savo_control Python tools."""

from .file_utils import (
    directory_exists,
    ensure_directory,
    ensure_parent_dir,
    file_exists,
    list_files,
    read_json_file,
    read_text_file,
    read_yaml_file,
    relative_to_root,
    safe_unlink,
    write_json_file,
    write_text_file,
    write_yaml_file,
)
from .math_utils import (
    apply_deadband,
    clamp,
    clamp_abs,
    finite_or_zero,
    hypot2,
    lerp,
    near_zero,
    safe_divide,
    shortest_angle_error_rad,
    sign,
    within_tolerance,
    wrap_angle_rad,
)
from .time_utils import (
    TimeCheck,
    age_s,
    check_age,
    clamp_dt,
    is_fresh,
    is_stale,
    now_s,
    safe_rate_period_s,
)
from .validation import (
    require_bool,
    require_choice,
    require_keys,
    require_mapping,
    require_non_empty_string,
    require_non_negative_float,
    require_positive_float,
    sanitize_float,
    validate_limits,
    validate_rate,
    validate_timeout,
    validate_topic_name,
)

__all__ = [
    "TimeCheck",
    "age_s",
    "apply_deadband",
    "check_age",
    "clamp",
    "clamp_abs",
    "clamp_dt",
    "directory_exists",
    "ensure_directory",
    "ensure_parent_dir",
    "file_exists",
    "finite_or_zero",
    "hypot2",
    "is_fresh",
    "is_stale",
    "lerp",
    "list_files",
    "near_zero",
    "now_s",
    "read_json_file",
    "read_text_file",
    "read_yaml_file",
    "relative_to_root",
    "require_bool",
    "require_choice",
    "require_keys",
    "require_mapping",
    "require_non_empty_string",
    "require_non_negative_float",
    "require_positive_float",
    "safe_divide",
    "safe_rate_period_s",
    "safe_unlink",
    "sanitize_float",
    "shortest_angle_error_rad",
    "sign",
    "validate_limits",
    "validate_rate",
    "validate_timeout",
    "validate_topic_name",
    "within_tolerance",
    "wrap_angle_rad",
    "write_json_file",
    "write_text_file",
    "write_yaml_file",
]
