network:
  version: 2
  renderer: networkd
  ethernets:
    "@CORE_ETH_IFACE@":
      dhcp4: false
      dhcp6: false
      addresses:
        - "@CORE_ETH_IP@/@LINK_PREFIX@"
      optional: true
      link-local: []
  wifis:
    "@CORE_WIFI_IFACE@":
      dhcp4: true
      optional: true
      access-points:
        "@WIFI_SSID@":
          password: "@WIFI_PASSWORD@"
