#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""ROS adapters and contracts for Robot Savo mapping."""

from __future__ import annotations

from .adapters import (
    apriltag_status_msg,
    bool_from_msg,
    bool_msg,
    exploration_goal_to_pose_msg,
    exploration_status_msg,
    from_json_string,
    json_from_msg,
    json_msg,
    location_bridge_status_msg,
    map_metadata_from_occupancy_grid,
    map_quality_from_occupancy_grid,
    map_quality_msg,
    mapping_status_msg,
    occupancy_grid_summary,
    pointcloud_status_msg,
    pointcloud_summary,
    pose_stamped_msg,
    pose_stamped_to_dict,
    readiness_state_msg,
    scan_summary,
    semantic_landmark_msg,
    string_from_msg,
    string_msg,
    to_json_string,
    yaw_to_quaternion_z_w,
)
from .params import (
    FrontierExplorerParams,
    MappingModeManagerParams,
    MappingSupervisorParams,
    PointcloudMonitorParams,
    build_default_param_bundle,
    frontier_explorer_params_from_dict,
    mapping_mode_manager_params_from_dict,
    mapping_supervisor_params_from_dict,
    pointcloud_monitor_params_from_dict,
)
from .qos_profiles import (
    default_qos,
    get_qos_profile,
    get_topic_qos_profile,
    map_metadata_qos,
    map_qos,
    pointcloud_qos,
    qos_config_to_profile,
    reliable_qos,
    scan_qos,
    sensor_data_qos,
    status_qos,
    tf_static_qos,
    transient_local_qos,
)
from .topic_contract import (
    DEFAULT_TOPIC_CONTRACT,
    MappingTopicContract,
    TopicSpec,
    build_default_topic_contract,
    get_mapping_topic_contract,
    get_optional_topic_names,
    get_publication_topic_names,
    get_required_topic_names,
    get_subscription_topic_names,
    validate_contract_topics,
)


__all__ = [
    # adapters
    "to_json_string",
    "from_json_string",
    "bool_msg",
    "string_msg",
    "json_msg",
    "bool_from_msg",
    "string_from_msg",
    "json_from_msg",
    "pose_stamped_msg",
    "yaw_to_quaternion_z_w",
    "pose_stamped_to_dict",
    "mapping_status_msg",
    "readiness_state_msg",
    "map_quality_msg",
    "pointcloud_status_msg",
    "exploration_status_msg",
    "apriltag_status_msg",
    "semantic_landmark_msg",
    "location_bridge_status_msg",
    "exploration_goal_to_pose_msg",
    "occupancy_grid_summary",
    "map_quality_from_occupancy_grid",
    "map_metadata_from_occupancy_grid",
    "scan_summary",
    "pointcloud_summary",
    # params
    "MappingSupervisorParams",
    "MappingModeManagerParams",
    "FrontierExplorerParams",
    "PointcloudMonitorParams",
    "mapping_supervisor_params_from_dict",
    "mapping_mode_manager_params_from_dict",
    "frontier_explorer_params_from_dict",
    "pointcloud_monitor_params_from_dict",
    "build_default_param_bundle",
    # qos
    "qos_config_to_profile",
    "get_qos_profile",
    "get_topic_qos_profile",
    "sensor_data_qos",
    "reliable_qos",
    "transient_local_qos",
    "default_qos",
    "scan_qos",
    "pointcloud_qos",
    "map_qos",
    "map_metadata_qos",
    "status_qos",
    "tf_static_qos",
    # topic contract
    "TopicSpec",
    "MappingTopicContract",
    "build_default_topic_contract",
    "DEFAULT_TOPIC_CONTRACT",
    "get_mapping_topic_contract",
    "get_required_topic_names",
    "get_optional_topic_names",
    "get_publication_topic_names",
    "get_subscription_topic_names",
    "validate_contract_topics",
]