savo_ui_node:
  ros__parameters:
    robot_name: "SAVO"
    framebuffer_device: "/dev/fb0"
    asset_root: ""
    preview_output_dir: "/tmp/savo_ui_preview"

    screen_width: 800
    screen_height: 480

    loop_hz: 10.0
    intro_seconds: 4.0
    robot360_seconds_per_frame: 4.0
    preview_animation_frames: 120

    enable_framebuffer: false
    enable_touch: false
    export_preview_frames: true
