lidar_filter_node:
  ros__parameters:
    input_scan_topic: "/scan"
    output_scan_topic: "/scan_filtered"
    scan_quality_topic: "/savo_lidar/scan_quality"

    min_range_m: 0.15
    max_range_m: 12.0

    # valid-ratio thresholds for scan quality status
    warn_valid_ratio: 0.60
    error_valid_ratio: 0.30