<?xml version="1.0"?>
<package format="3">
  <name>savo_bringup</name>
  <version>0.2.0</version>
  <description>Production launch and deployment wiring for Robot Savo.</description>

  <maintainer email="todo@example.com">TODO_NAME</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>rclpy</exec_depend>

  <exec_depend>savo_head</exec_depend>
  <exec_depend>savo_locations</exec_depend>
  <exec_depend>savo_mapping</exec_depend>
  <exec_depend>savo_msgs</exec_depend>
  <exec_depend>savo_nav</exec_depend>
  <exec_depend>savo_supervisor</exec_depend>

  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
