#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""Utility helpers for Robot Savo mapping."""

from __future__ import annotations

from .diagnostics import (
    DiagnosticItem,
    DiagnosticLevel,
    DiagnosticReport,
    build_diagnostic_report,
    format_diagnostic_report,
    make_disabled,
    make_error,
    make_ok,
    make_stale,
    make_warn,
    merge_reports,
)
from .logging import (
    LoggerConfig,
    configure_logger,
    get_logger,
    log_key_value,
    log_section,
    log_status_dict,
    normalize_log_level,
    set_logger_level,
)
from .param_loader import (
    deep_merge_dicts,
    get_nested,
    get_ros_parameters,
    load_profile,
    load_profile_stack,
    load_ros_parameters,
    load_yaml_file,
    load_yaml_files,
    merge_ros_parameter_files,
    require_file,
    require_mapping,
    require_nested,
    resolve_path,
    save_yaml_file,
    set_nested,
)
from .qos import (
    DEFAULT_QOS,
    QOS_DEFAULT,
    QOS_RELIABLE,
    QOS_SENSOR_DATA,
    QOS_TRANSIENT_LOCAL,
    RELIABLE_QOS,
    SENSOR_DATA_QOS,
    TRANSIENT_LOCAL_QOS,
    QosConfig,
    get_qos_config,
    get_rclpy_qos,
    list_qos_profiles,
    qos_name_for_topic,
    to_rclpy_qos,
)
from .ratekeeper import (
    LoopBudget,
    Ratekeeper,
)
from .timing import (
    RateTracker,
    SimpleTimer,
    StaleMonitor,
    age_s,
    is_stale,
    monotonic_s,
    now_s,
)
from .topic_names import (
    CORE_TOPICS,
    DEFAULT_TOPIC_GROUPS,
    EDGE_REALSENSE_TOPICS,
    MAPPING_OUTPUT_TOPICS,
    NAV2_TOPICS,
    SEMANTIC_TOPICS,
    TRANSFORM_TOPICS,
    MappingTopicGroups,
    ensure_topic_namespace,
    get_all_mapping_topics,
    get_mapping_topic_groups,
    get_topic,
    is_absolute_topic,
    is_private_topic,
    join_topic,
    normalize_topic,
    normalize_topic_map,
    topic_basename,
    topic_namespace,
    validate_topics,
)


__all__ = [
    # topic names
    "MappingTopicGroups",
    "CORE_TOPICS",
    "TRANSFORM_TOPICS",
    "EDGE_REALSENSE_TOPICS",
    "MAPPING_OUTPUT_TOPICS",
    "SEMANTIC_TOPICS",
    "NAV2_TOPICS",
    "DEFAULT_TOPIC_GROUPS",
    "is_absolute_topic",
    "is_private_topic",
    "normalize_topic",
    "join_topic",
    "topic_basename",
    "topic_namespace",
    "ensure_topic_namespace",
    "normalize_topic_map",
    "validate_topics",
    "get_mapping_topic_groups",
    "get_all_mapping_topics",
    "get_topic",
    # params
    "resolve_path",
    "require_file",
    "load_yaml_file",
    "load_yaml_files",
    "save_yaml_file",
    "deep_merge_dicts",
    "get_nested",
    "require_nested",
    "set_nested",
    "require_mapping",
    "get_ros_parameters",
    "load_ros_parameters",
    "merge_ros_parameter_files",
    "load_profile",
    "load_profile_stack",
    # timing
    "now_s",
    "monotonic_s",
    "age_s",
    "is_stale",
    "RateTracker",
    "StaleMonitor",
    "SimpleTimer",
    # ratekeeper
    "Ratekeeper",
    "LoopBudget",
    # logging
    "LoggerConfig",
    "normalize_log_level",
    "configure_logger",
    "get_logger",
    "set_logger_level",
    "log_key_value",
    "log_section",
    "log_status_dict",
    # diagnostics
    "DiagnosticLevel",
    "DiagnosticItem",
    "DiagnosticReport",
    "make_ok",
    "make_warn",
    "make_error",
    "make_stale",
    "make_disabled",
    "build_diagnostic_report",
    "merge_reports",
    "format_diagnostic_report",
    # qos
    "QOS_DEFAULT",
    "QOS_SENSOR_DATA",
    "QOS_RELIABLE",
    "QOS_TRANSIENT_LOCAL",
    "QosConfig",
    "DEFAULT_QOS",
    "SENSOR_DATA_QOS",
    "RELIABLE_QOS",
    "TRANSIENT_LOCAL_QOS",
    "get_qos_config",
    "list_qos_profiles",
    "to_rclpy_qos",
    "get_rclpy_qos",
    "qos_name_for_topic",
]