#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""Utility helpers for savo_perception Python fallback nodes and diagnostics."""

from __future__ import annotations

from savo_perception.utils.clamp import (
    clamp,
    clamp01,
    clamp_abs,
    clamp_slowdown,
    safe_float,
    safe_positive_float,
    safe_rate_hz,
    valid_distance_m,
    valid_unit_interval,
)
from savo_perception.utils.diagnostics import (
    DiagnosticEvent,
    DiagnosticSummary,
    event_from_exception,
    format_status_line,
    merge_summaries,
)
from savo_perception.utils.param_loader import (
    ParamLoadResult,
    coerce_hex_int,
    config_path_exists,
    deep_merge,
    drop_none_values,
    extract_ros_parameters,
    flatten_nested,
    get_nested,
    is_yaml_available,
    load_config_file,
    load_json_file,
    load_ros_params_file,
    load_yaml_file,
    merge_many,
    normalize_node_name,
    overlay_params,
    pick_keys,
    require_keys,
)
from savo_perception.utils.qos import (
    describe_qos_key,
    is_ros_qos_available,
    qos_cmd_vel,
    qos_debug_best_effort,
    qos_depth_sensor,
    qos_diag_event,
    qos_diag_state,
    qos_for_key,
    qos_heartbeat,
    qos_latched_status,
    qos_range_sensor,
    qos_safety_bool,
    qos_slowdown_factor,
    qos_state_string,
)
from savo_perception.utils.ratekeeper import (
    RateKeeper,
    monotonic_s,
)
from savo_perception.utils.timing import (
    FreshnessTracker,
    LoopStats,
    age_s,
    elapsed_s,
    is_stale,
    now_mono_s,
    now_wall_s,
    rate_to_period_s,
    sleep_remaining,
)
from savo_perception.utils.topic_names import (
    CMD_VEL,
    CMD_VEL_SAFE,
    DEPTH_FRONT_M,
    ODOM_FILTERED,
    PERCEPTION_SAFETY_TOPICS,
    PERCEPTION_STATUS_TOPICS,
    RANGE_SENSOR_TOPICS,
    SAFETY_SLOWDOWN_FACTOR,
    SAFETY_STOP,
    SAVO_PERCEPTION_DASHBOARD,
    SAVO_PERCEPTION_DASHBOARD_TEXT,
    SAVO_PERCEPTION_DIAG,
    SAVO_PERCEPTION_HEARTBEAT,
    SAVO_PERCEPTION_RANGE_HEALTH,
    SAVO_PERCEPTION_SAFETY_STATE,
    SAVO_PERCEPTION_SENSOR_STATUS,
    TOF_LEFT_M,
    TOF_RIGHT_M,
    ULTRASONIC_FRONT_M,
    VO_ODOM,
    PerceptionSafetyTopics,
    PerceptionStatusTopics,
    RangeSensorTopics,
    join_topic,
    normalize_topic_name,
    prefixed_topic_bundle,
    remap_topic_dict,
    topic_in_namespace,
    validate_topic_names,
)


__all__ = [
    # clamp
    "clamp",
    "clamp01",
    "clamp_abs",
    "clamp_slowdown",
    "safe_float",
    "safe_positive_float",
    "safe_rate_hz",
    "valid_distance_m",
    "valid_unit_interval",
    # diagnostics
    "DiagnosticEvent",
    "DiagnosticSummary",
    "event_from_exception",
    "format_status_line",
    "merge_summaries",
    # param loader
    "ParamLoadResult",
    "coerce_hex_int",
    "config_path_exists",
    "deep_merge",
    "drop_none_values",
    "extract_ros_parameters",
    "flatten_nested",
    "get_nested",
    "is_yaml_available",
    "load_config_file",
    "load_json_file",
    "load_ros_params_file",
    "load_yaml_file",
    "merge_many",
    "normalize_node_name",
    "overlay_params",
    "pick_keys",
    "require_keys",
    # qos
    "describe_qos_key",
    "is_ros_qos_available",
    "qos_cmd_vel",
    "qos_debug_best_effort",
    "qos_depth_sensor",
    "qos_diag_event",
    "qos_diag_state",
    "qos_for_key",
    "qos_heartbeat",
    "qos_latched_status",
    "qos_range_sensor",
    "qos_safety_bool",
    "qos_slowdown_factor",
    "qos_state_string",
    # rate / timing
    "RateKeeper",
    "monotonic_s",
    "FreshnessTracker",
    "LoopStats",
    "age_s",
    "elapsed_s",
    "is_stale",
    "now_mono_s",
    "now_wall_s",
    "rate_to_period_s",
    "sleep_remaining",
    # topic names
    "CMD_VEL",
    "CMD_VEL_SAFE",
    "DEPTH_FRONT_M",
    "ODOM_FILTERED",
    "PERCEPTION_SAFETY_TOPICS",
    "PERCEPTION_STATUS_TOPICS",
    "RANGE_SENSOR_TOPICS",
    "SAFETY_SLOWDOWN_FACTOR",
    "SAFETY_STOP",
    "SAVO_PERCEPTION_DASHBOARD",
    "SAVO_PERCEPTION_DASHBOARD_TEXT",
    "SAVO_PERCEPTION_DIAG",
    "SAVO_PERCEPTION_HEARTBEAT",
    "SAVO_PERCEPTION_RANGE_HEALTH",
    "SAVO_PERCEPTION_SAFETY_STATE",
    "SAVO_PERCEPTION_SENSOR_STATUS",
    "TOF_LEFT_M",
    "TOF_RIGHT_M",
    "ULTRASONIC_FRONT_M",
    "VO_ODOM",
    "PerceptionSafetyTopics",
    "PerceptionStatusTopics",
    "RangeSensorTopics",
    "join_topic",
    "normalize_topic_name",
    "prefixed_topic_bundle",
    "remap_topic_dict",
    "topic_in_namespace",
    "validate_topic_names",
]